export type RootStackParamList = {
    Splash: undefined;
    HomeTabs: undefined;
    Login: undefined;
    SignUp: undefined;
    ScanningScreen: undefined;
    QuickScanDevices: undefined;
    PairedDevices: undefined;
    Home: undefined;
    Steps: undefined;
    Weather: undefined;
    LMS: undefined;
    Profile: undefined;
    PersonalInfo: undefined;
    ChangePassword: undefined;
    BMIResult: { bmi: string };
    BMI: undefined;
    Nutrition: undefined;
    EditProfile: undefined;
    Subjects: undefined;
    SubjectDetailScreen: undefined;
    TopicDetailScreen: undefined;
    LessonsPage: undefined;
};